// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjWYFSRzdyOwKnvUMCwBRBBV-BI8iCC4',
    appId: '1:96845289438:web:83b1a2be2fb31367d2ef4f',
    messagingSenderId: '96845289438',
    projectId: 'timetask-4dde2',
    authDomain: 'timetask-4dde2.firebaseapp.com',
    storageBucket: 'timetask-4dde2.appspot.com',
    measurementId: 'G-SVVYT9WG5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-TYx5wgqO5g7AuAHXT3kMeHFoaCFnu5E',
    appId: '1:96845289438:android:90c60ff6ed0161f5d2ef4f',
    messagingSenderId: '96845289438',
    projectId: 'timetask-4dde2',
    storageBucket: 'timetask-4dde2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6vJCPLe0Dd-M1SppIzed0oA6jrq6lD1I',
    appId: '1:96845289438:ios:f0d6468691dcce4bd2ef4f',
    messagingSenderId: '96845289438',
    projectId: 'timetask-4dde2',
    storageBucket: 'timetask-4dde2.appspot.com',
    iosClientId: '96845289438-e094pj6vqdjqk1link4i09pgg75ecqov.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6vJCPLe0Dd-M1SppIzed0oA6jrq6lD1I',
    appId: '1:96845289438:ios:f0d6468691dcce4bd2ef4f',
    messagingSenderId: '96845289438',
    projectId: 'timetask-4dde2',
    storageBucket: 'timetask-4dde2.appspot.com',
    iosClientId: '96845289438-e094pj6vqdjqk1link4i09pgg75ecqov.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDjWYFSRzdyOwKnvUMCwBRBBV-BI8iCC4',
    appId: '1:96845289438:web:35a169876057ba64d2ef4f',
    messagingSenderId: '96845289438',
    projectId: 'timetask-4dde2',
    authDomain: 'timetask-4dde2.firebaseapp.com',
    storageBucket: 'timetask-4dde2.appspot.com',
    measurementId: 'G-LX8Z2ZTM5L',
  );
}
